version: '3.4'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  sat.recruitment.api:
    image: ${DOCKER_REGISTRY-}satrecruitmentapi
    build:
      context: .
      dockerfile: Sat.Recruitment.Api/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  elasticsearch-data: