version: '3.4'

services:
  sat.recruitment.api:
    container_name: Sat.Recruitment.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - ASPNETCORE_HTTPS_PORT=9001
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings:SatRecruitmentConnectionString=Server=sqldb;Database=sat_recruitment_db;User Id=sa;Password=P@ssword1"
    depends_on:
      - sqldb
    ports:
      - "6000:80"
      - "9001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqldb:
    container_name: sqldb
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    restart: always
    ports: 
      - "1433:1433"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
        - xpack.security.enabled=false
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"